<?php
$countries = array(
    array('name' => 'Австралия', 'share' => 'в Австралии', 'flag' => 'Australia.jpg'),
    array('name' => 'Австрия', 'share' => 'в Австрии', 'flag' => 'Austria.jpg'),
    array('name' => 'Азербайджан', 'share' => 'в Азербайджане', 'flag' => 'Azerbaijan.jpg'),
    array('name' => 'Албания', 'share' => 'в Албании', 'flag' => 'Albania.jpg'),
    array('name' => 'Алжир', 'share' => 'в Алжире', 'flag' => 'Algeria.jpg'),
    array('name' => 'Ангола', 'share' => 'в Анголе', 'flag' => 'Angola.jpg'),
    array('name' => 'Андорра', 'share' => 'в Андорре', 'flag' => 'Andorra.jpg'),
    array('name' => 'Антигуа и Барбуда', 'share' => 'в Антигуа и Барбуда', 'flag' => 'Antigua_and_Barbuda.jpg'),
    array('name' => 'Аргентина', 'share' => 'в Аргентине', 'flag' => 'Argentina.jpg'),
    array('name' => 'Армения', 'share' => 'в Армении', 'flag' => 'Armenia.jpg'),
    array('name' => 'Афганистан', 'share' => 'в Афганистане', 'flag' => 'Afghanistan.jpg'),
    array('name' => 'Багамы', 'share' => 'на Багамах', 'flag' => 'Bahamas.jpg'),
    array('name' => 'Бангладеш', 'share' => 'в Бангладеш', 'flag' => 'Bangladesh.jpg'),
    array('name' => 'Барбадос', 'share' => 'в Барбадосе', 'flag' => 'Barbados.jpg'),
    array('name' => 'Бахрейн', 'share' => 'в Бахрейне', 'flag' => 'Bahrain.jpg'),
    array('name' => 'Белиз', 'share' => 'в Белизе', 'flag' => 'Belize.jpg'),
    array('name' => 'Белоруссия', 'share' => 'в Белоруссии', 'flag' => 'Belarus.jpg'),
    array('name' => 'Бельгия', 'share' => 'в Бельгии', 'flag' => 'Belgium.jpg'),
    array('name' => 'Бенин', 'share' => 'в Бенине', 'flag' => 'Benin.jpg'),
    array('name' => 'Болгария', 'share' => 'в Болгарии', 'flag' => 'Bulgaria.jpg'),
    array('name' => 'Боливия', 'share' => 'в Боливии', 'flag' => 'Bolivia.jpg'),
    array('name' => 'Босния и Герцеговина', 'share' => 'в Боснии и Герцеговине', 'flag' => 'Bosnia_and_Herzegovina.jpg'),
    array('name' => 'Ботсвана', 'share' => 'в Ботсване', 'flag' => 'Botswana.jpg'),
    array('name' => 'Бразилия', 'share' => 'в Бразилии', 'flag' => 'Brazil.jpg'),
    array('name' => 'Бруней', 'share' => 'в Брунее', 'flag' => 'Brunei.jpg'),
    array('name' => 'Буркина-Фасо', 'share' => 'в Буркина-Фасо', 'flag' => 'Burkina_Faso.jpg'),
    array('name' => 'Бурунди', 'share' => 'в Бурунди', 'flag' => 'Burundi.jpg'),
    array('name' => 'Бутан', 'share' => 'в Бутане', 'flag' => 'Bhutan.jpg'),
    array('name' => 'Вануату', 'share' => 'в Вануату', 'flag' => 'Vanuatu.jpg'),
    array('name' => 'Великобритания', 'share' => 'в Великобритании', 'flag' => 'United_Kingdom.jpg'),
    array('name' => 'Венгрия', 'share' => 'в Венгрии', 'flag' => 'Hungary.jpg'),
    array('name' => 'Венесуэла', 'share' => 'в Венесуэле', 'flag' => 'Venezuela.jpg'),
    array('name' => 'Восточный Тимор', 'share' => 'в Восточном Тиморе', 'flag' => 'East_Timor.jpg'),
    array('name' => 'Вьетнам', 'share' => 'во Вьетнаме', 'flag' => 'Vietnam.jpg'),
    array('name' => 'Габон', 'share' => 'в Габоне', 'flag' => 'Gabon.jpg'),
    array('name' => 'Гаити', 'share' => 'на Гаити', 'flag' => 'Haiti.jpg'),
    array('name' => 'Гайана', 'share' => 'в Гайане', 'flag' => 'Guyana.jpg'),
    array('name' => 'Гамбия', 'share' => 'в Гамбии', 'flag' => 'Gambia.jpg'),
    array('name' => 'Гана', 'share' => 'в Гане', 'flag' => 'Ghana.jpg'),
    array('name' => 'Гватемала', 'share' => 'в Гватемале', 'flag' => 'Guatemala.jpg'),
    array('name' => 'Гвинея', 'share' => 'в Гвинее', 'flag' => 'Guinea.jpg'),
    array('name' => 'Гвинея-Бисау', 'share' => 'в Гвинее-Бисау', 'flag' => 'Guinea-Bissau.jpg'),
    array('name' => 'Германия', 'share' => 'в Германии', 'flag' => 'Germany.jpg'),
    array('name' => 'Гондурас', 'share' => 'в Гондурасе', 'flag' => 'Honduras.jpg'),
    array('name' => 'Гренада', 'share' => 'в Гренаде', 'flag' => 'Grenada.jpg'),
    array('name' => 'Греция', 'share' => 'в Греции', 'flag' => 'Greece.jpg'),
    array('name' => 'Грузия', 'share' => 'в Грузии', 'flag' => 'Georgia.jpg'),
    array('name' => 'Дания', 'share' => 'в Дании', 'flag' => 'Denmark.jpg'),
    array('name' => 'Демократическая Республика Конго', 'share' => 'в Демократической Республике Конго', 'flag' => 'Democratic_Republic_of_the_Congo.jpg'),
    array('name' => 'Джибути', 'share' => 'в Джибути', 'flag' => 'Djibouti.jpg'),
    array('name' => 'Доминика', 'share' => 'в Доминике', 'flag' => 'Dominica.jpg'),
    array('name' => 'Доминиканская Республика', 'share' => 'в Доминиканской Республике', 'flag' => 'Dominican_Republic.jpg'),
    array('name' => 'Египет', 'share' => 'в Египте', 'flag' => 'Egypt.jpg'),
    array('name' => 'Замбия', 'share' => 'в Замбии', 'flag' => 'Zambia.jpg'),
    array('name' => 'Зимбабве', 'share' => 'в Зимбабве', 'flag' => 'Zimbabwe.jpg'),
    array('name' => 'Израиль', 'share' => 'в Израиле', 'flag' => 'Israel.jpg'),
    array('name' => 'Индия', 'share' => 'в Индии', 'flag' => 'India.jpg'),
    array('name' => 'Индонезия', 'share' => 'в Индонезии', 'flag' => 'Indonesia.jpg'),
    array('name' => 'Иордания', 'share' => 'в Иордании', 'flag' => 'Jordan.jpg'),
    array('name' => 'Ирак', 'share' => 'в Ираке', 'flag' => 'Iraq.jpg'),
    array('name' => 'Иран', 'share' => 'в Иране', 'flag' => 'Iran.jpg'),
    array('name' => 'Ирландия', 'share' => 'в Ирландии', 'flag' => 'Ireland.jpg'),
    array('name' => 'Исландия', 'share' => 'в Исландии', 'flag' => 'Iceland.jpg'),
    array('name' => 'Испания', 'share' => 'в Испании', 'flag' => 'Spain.jpg'),
    array('name' => 'Италия', 'share' => 'в Италии', 'flag' => 'Italy.jpg'),
    array('name' => 'Йемен', 'share' => 'в Йемене', 'flag' => 'Yemen.jpg'),
    array('name' => 'Кабо-Верде', 'share' => 'в Кабо-Верде', 'flag' => 'Cape_Verde.jpg'),
    array('name' => 'Казахстан', 'share' => 'в Казахстане', 'flag' => 'Kazakhstan.jpg'),
    array('name' => 'Камбоджа', 'share' => 'в Камбодже', 'flag' => 'Cambodia.jpg'),
    array('name' => 'Камерун', 'share' => 'в Камеруне', 'flag' => 'Cameroon.jpg'),
    array('name' => 'Канада', 'share' => 'в Канаде', 'flag' => 'Canada.jpg'),
    array('name' => 'Катар', 'share' => 'в Катаре', 'flag' => 'Qatar.jpg'),
    array('name' => 'Кения', 'share' => 'в Кении', 'flag' => 'Kenya.jpg'),
    array('name' => 'Кипр', 'share' => 'на Кипре', 'flag' => 'Cyprus.jpg'),
    array('name' => 'Киргизия', 'share' => 'в Киргизии', 'flag' => 'Kyrgyzstan.jpg'),
    array('name' => 'Кирибати', 'share' => 'в Кирибати', 'flag' => 'Kiribati.jpg'),
    array('name' => 'КНДР', 'share' => 'в КНДР', 'flag' => 'North_Korea.jpg'),
    array('name' => 'КНР', 'share' => 'в КНР', 'flag' => 'China.jpg'),
    array('name' => 'Колумбия', 'share' => 'в Колумбии', 'flag' => 'Colombia.jpg'),
    array('name' => 'Коморы', 'share' => 'на Коморы', 'flag' => 'Comoros.jpg'),
    array('name' => 'Коста-Рика', 'share' => 'в Коста-Рике', 'flag' => 'Costa_Rica.jpg'),
    array('name' => 'Кот-д’Ивуар', 'share' => 'в Кот-д’Ивуаре', 'flag' => 'Cote_dIvoire.jpg'),
    array('name' => 'Куба', 'share' => 'в Кубе', 'flag' => 'Cuba.jpg'),
    array('name' => 'Кувейт', 'share' => 'в Кувейте', 'flag' => 'Kuwait.jpg'),
    array('name' => 'Лаос', 'share' => 'в Лаосе', 'flag' => 'Laos.jpg'),
    array('name' => 'Латвия', 'share' => 'в Латвии', 'flag' => 'Latvia.jpg'),
    array('name' => 'Лесото', 'share' => 'в Лесото', 'flag' => 'Lesotho.jpg'),
    array('name' => 'Либерия', 'share' => 'в Либерии', 'flag' => 'Liberia.jpg'),
    array('name' => 'Ливан', 'share' => 'в Ливане', 'flag' => 'Lebanon.jpg'),
    array('name' => 'Ливия', 'share' => 'в Ливии', 'flag' => 'Libya.jpg'),
    array('name' => 'Литва', 'share' => 'в Литве', 'flag' => 'Lithuania.jpg'),
    array('name' => 'Лихтенштейн', 'share' => 'в Лихтенштейне', 'flag' => 'Liechtenstein.jpg'),
    array('name' => 'Люксембург', 'share' => 'в Люксембурге', 'flag' => 'Luxembourg.jpg'),
    array('name' => 'Маврикий', 'share' => 'на Маврикии', 'flag' => 'Mauritius.jpg'),
    array('name' => 'Мавритания', 'share' => 'в Мавритании', 'flag' => 'Mauritania.jpg'),
    array('name' => 'Мадагаскар', 'share' => 'в Мадагаскаре', 'flag' => 'Madagascar.jpg'),
    array('name' => 'Македония', 'share' => 'в Македонии', 'flag' => 'Macedonia.jpg'),
    array('name' => 'Малави', 'share' => 'в Малави', 'flag' => 'Malawi.jpg'),
    array('name' => 'Малайзия', 'share' => 'в Малайзии', 'flag' => 'Malaysia.jpg'),
    array('name' => 'Мали', 'share' => 'в Мали', 'flag' => 'Mali.jpg'),
    array('name' => 'Мальдивы', 'share' => 'на Мальдивах', 'flag' => 'Maldives.jpg'),
    array('name' => 'Мальта', 'share' => 'на Мальте', 'flag' => 'Malta.jpg'),
    array('name' => 'Марокко', 'share' => 'в Марокко', 'flag' => 'Morocco.jpg'),
    array('name' => 'Маршалловы Острова', 'share' => 'в Маршалловых Островах', 'flag' => 'Marshall_Islands.jpg'),
    array('name' => 'Мексика', 'share' => 'в Мексике', 'flag' => 'Mexico.jpg'),
    array('name' => 'Мозамбик', 'share' => 'в Мозамбике', 'flag' => 'Mozambique.jpg'),
    array('name' => 'Молдавия', 'share' => 'в Молдавии', 'flag' => 'Moldova.jpg'),
    array('name' => 'Монако', 'share' => 'в Монако', 'flag' => 'Monaco.jpg'),
    array('name' => 'Монголия', 'share' => 'в Монголии', 'flag' => 'Mongolia.jpg'),
    array('name' => 'Мьянма', 'share' => 'в Мьянме', 'flag' => 'Myanmar.jpg'),
    array('name' => 'Намибия', 'share' => 'в Намибии', 'flag' => 'Namibia.jpg'),
    array('name' => 'Науру', 'share' => 'в Науру', 'flag' => 'Nauru.jpg'),
    array('name' => 'Непал', 'share' => 'в Непале', 'flag' => 'Nepal.jpg'),
    array('name' => 'Нигер', 'share' => 'в Нигере', 'flag' => 'Niger.jpg'),
    array('name' => 'Нигерия', 'share' => 'в Нигерии', 'flag' => 'Nigeria.jpg'),
    array('name' => 'Нидерланды', 'share' => 'в Нидерландах', 'flag' => 'Netherlands.jpg'),
    array('name' => 'Никарагуа', 'share' => 'в Никарагуа', 'flag' => 'Nicaragua.jpg'),
    array('name' => 'Новая Зеландия', 'share' => 'в Новой Зеландии', 'flag' => 'New_Zealand.jpg'),
    array('name' => 'Норвегия', 'share' => 'в Норвегии', 'flag' => 'Norway.jpg'),
    array('name' => 'ОАЭ', 'share' => 'в ОАЭ', 'flag' => 'United_Arab_Emirates.jpg'),
    array('name' => 'Оман', 'share' => 'в Омане', 'flag' => 'Oman.jpg'),
    array('name' => 'Пакистан', 'share' => 'в Пакистане', 'flag' => 'Pakistan.jpg'),
    array('name' => 'Палау', 'share' => 'в Палау', 'flag' => 'Palau.jpg'),
    array('name' => 'Панама', 'share' => 'на Панаме', 'flag' => 'Panama.jpg'),
    array('name' => 'Папуа — Новая Гвинея', 'share' => 'в Папуа — Новой Гвинее', 'flag' => 'Papua_New_Guinea.jpg'),
    array('name' => 'Парагвай', 'share' => 'в Парагвае', 'flag' => 'Paraguay.jpg'),
    array('name' => 'Перу', 'share' => 'в Перу', 'flag' => 'Peru.jpg'),
    array('name' => 'Польша', 'share' => 'в Польше', 'flag' => 'Poland.jpg'),
    array('name' => 'Португалия', 'share' => 'в Португалии', 'flag' => 'Portugal.jpg'),
    array('name' => 'Республика Конго', 'share' => 'в Республике Конго', 'flag' => 'Republic_of_the_Congo.jpg'),
    array('name' => 'Республика Корея', 'share' => 'в Республике Корея', 'flag' => 'South_Korea.jpg'),
    array('name' => 'Россия', 'share' => 'в России', 'flag' => 'Russia.jpg'),
    array('name' => 'Руанда', 'share' => 'в Руанде', 'flag' => 'Rwanda.jpg'),
    array('name' => 'Румыния', 'share' => 'в Румынии', 'flag' => 'Romania.jpg'),
    array('name' => 'Сальвадор', 'share' => 'в Сальвадоре', 'flag' => 'El_Salvador.jpg'),
    array('name' => 'Самоа', 'share' => 'в Самоа', 'flag' => 'Samoa.jpg'),
    array('name' => 'Сан-Марино', 'share' => 'в Сан-Марино', 'flag' => 'San_Marino.jpg'),
    array('name' => 'Сан-Томе и Принсипи', 'share' => 'в Сан-Томе и Принсипи', 'flag' => 'Sao_Tome_and_Principe.jpg'),
    array('name' => 'Саудовская Аравия', 'share' => 'в Саудовской Аравии', 'flag' => 'Saudi_Arabia.jpg'),
    array('name' => 'Свазиленд', 'share' => 'Свазиленде', 'flag' => 'Swaziland.jpg'),
    array('name' => 'Сейшельские Острова', 'share' => 'на Сейшельских Островах', 'flag' => 'Seychelles.jpg'),
    array('name' => 'Сенегал', 'share' => 'в Сенегале', 'flag' => 'Senegal.jpg'),
    array('name' => 'Сент-Винсент и Гренадины', 'share' => 'в Сент-Винсент и Гренадинах', 'flag' => 'Saint_Vincent_and_the_Grenadines.jpg'),
    array('name' => 'Сент-Китс и Невис', 'share' => 'в Сент-Китс и Невисе', 'flag' => 'Saint_Kitts_and_Nevis.jpg'),
    array('name' => 'Сент-Люсия', 'share' => 'в Сент-Люсии', 'flag' => 'Saint_Lucia.jpg'),
    array('name' => 'Сербия', 'share' => 'в Сербии', 'flag' => 'Serbia.jpg'),
    array('name' => 'Сингапур', 'share' => 'в Сингапуре', 'flag' => 'Singapore.jpg'),
    array('name' => 'Сирия', 'share' => 'в Сирии', 'flag' => 'Syria.jpg'),
    array('name' => 'Словакия', 'share' => 'в Словакии', 'flag' => 'Slovakia.jpg'),
    array('name' => 'Словения', 'share' => 'в Словении', 'flag' => 'Slovenia.jpg'),
    array('name' => 'Соломоновы Острова', 'share' => 'на Соломоновых Островах', 'flag' => 'Solomon_Islands.jpg'),
    array('name' => 'Сомали', 'share' => 'в Сомали', 'flag' => 'Somalia.jpg'),
    array('name' => 'Судан', 'share' => 'в Судане', 'flag' => 'Sudan.jpg'),
    array('name' => 'Суринам', 'share' => 'в Суринаме', 'flag' => 'Suriname.jpg'),
    array('name' => 'США', 'share' => 'в США', 'flag' => 'United_States.jpg'),
    array('name' => 'Сьерра-Леоне', 'share' => 'в Сьерра-Леоне', 'flag' => 'Sierra_Leone.jpg'),
    array('name' => 'Таджикистан', 'share' => 'в Таджикистане', 'flag' => 'Tajikistan.jpg'),
    array('name' => 'Таиланд', 'share' => 'в Таиланде', 'flag' => 'Thailand.jpg'),
    array('name' => 'Танзания', 'share' => 'в Танзании', 'flag' => 'Tanzania.jpg'),
    array('name' => 'Того', 'share' => 'в Того', 'flag' => 'Togo.jpg'),
    array('name' => 'Тонга', 'share' => 'в Тонга', 'flag' => 'Tonga.jpg'),
    array('name' => 'Тринидад и Тобаго', 'share' => 'в Тринидад и Тобаго', 'flag' => 'Trinidad_and_Tobago.jpg'),
    array('name' => 'Тувалу', 'share' => 'в Тувалу', 'flag' => 'Tuvalu.jpg'),
    array('name' => 'Тунис', 'share' => 'в Тунисе', 'flag' => 'Tunisia.jpg'),
    array('name' => 'Туркмения', 'share' => 'в Туркмении', 'flag' => 'Turkmenistan.jpg'),
    array('name' => 'Турция', 'share' => 'в Турции', 'flag' => 'Turkey.jpg'),
    array('name' => 'Уганда', 'share' => 'в Уганде', 'flag' => 'Uganda.jpg'),
    array('name' => 'Узбекистан', 'share' => 'в Узбекистане', 'flag' => 'Uzbekistan.jpg'),
    array('name' => 'Украина', 'share' => 'на Украине', 'flag' => 'Ukraine.jpg'),
    array('name' => 'Уругвай', 'share' => 'в Уругвае', 'flag' => 'Uruguay.jpg'),
    array('name' => 'Федеративные Штаты Микронезии', 'share' => 'в Федеративных Штатах Микронезии', 'flag' => 'Micronesia.jpg'),
    array('name' => 'Фиджи', 'share' => 'на Фиджи', 'flag' => 'Fiji.jpg'),
    array('name' => 'Филиппины', 'share' => 'на Филиппинах', 'flag' => 'Philippines.jpg'),
    array('name' => 'Финляндия', 'share' => 'в Финляндии', 'flag' => 'Finland.jpg'),
    array('name' => 'Франция', 'share' => 'во Франции', 'flag' => 'France.jpg'),
    array('name' => 'Хорватия', 'share' => 'в Хорватии', 'flag' => 'Croatia.jpg'),
    array('name' => 'Центральноафриканская Республика', 'share' => 'в Центральноафриканской Республике', 'flag' => 'Central_African_Republic.jpg'),
    array('name' => 'Чад', 'share' => 'в Чаде', 'flag' => 'Chad.jpg'),
    array('name' => 'Черногория', 'share' => 'в Черногории', 'flag' => 'Montenegro.jpg'),
    array('name' => 'Чехия', 'share' => 'в Чехии', 'flag' => 'Czech_Republic.jpg'),
    array('name' => 'Чили', 'share' => 'в Чили', 'flag' => 'Chile.jpg'),
    array('name' => 'Швейцария', 'share' => 'в Швейцарии', 'flag' => 'Switzerland.jpg'),
    array('name' => 'Швеция', 'share' => 'в Швеции', 'flag' => 'Sweden.jpg'),
    array('name' => 'Шри-Ланка', 'share' => 'на Шри-Ланке', 'flag' => 'Sri_Lanka.jpg'),
    array('name' => 'Эквадор', 'share' => 'в Эквадоре', 'flag' => 'Ecuador.jpg'),
    array('name' => 'Экваториальная Гвинея', 'share' => 'в Экваториальной Гвинее', 'flag' => 'Equatorial_Guinea.jpg'),
    array('name' => 'Эритрея', 'share' => 'в Эритрее', 'flag' => 'Eritrea.jpg'),
    array('name' => 'Эстония', 'share' => 'в Эстонии', 'flag' => 'Estonia.jpg'),
    array('name' => 'Эфиопия', 'share' => 'в Эфиопии', 'flag' => 'Ethiopia.jpg'),
    array('name' => 'ЮАР', 'share' => 'в ЮАР', 'flag' => 'South_Africa.jpg'),
    array('name' => 'Южный Судан', 'share' => 'в Южном Судане', 'flag' => 'South_Sudan.jpg'),
    array('name' => 'Ямайка', 'share' => 'на Ямайке', 'flag' => 'Jamaica.jpg'),
    array('name' => 'Япония', 'share' => 'в Японии', 'flag' => 'Japan.jpg')
);

return $countries;