<?php

require_once 'lib/Twig/Autoloader.php';
Twig_Autoloader::register();

$loader = new Twig_Loader_Filesystem('templates');
$twig = new Twig_Environment($loader, array(
    'cache'       => 'compilation_cache',
    'auto_reload' => true
));

$countries = array(
    array('name' => 'Австралия', 'flag' => 'Australia.jpg'),
    array('name' => 'Австрия', 'flag' => 'Austria.jpg'),
    array('name' => 'Азербайджан', 'flag' => 'Azerbaijan.jpg'),
    array('name' => 'Албания', 'flag' => 'Albania.jpg'),
    array('name' => 'Алжир', 'flag' => 'Algeria.jpg'),
    array('name' => 'Ангола', 'flag' => 'Angola.jpg'),
    array('name' => 'Андорра', 'flag' => 'Andorra.jpg'),
    array('name' => 'Антигуа и Барбуда', 'flag' => 'Antigua_and_Barbuda.jpg'),
    array('name' => 'Аргентина', 'flag' => 'Argentina.jpg'),
    array('name' => 'Армения', 'flag' => 'Armenia.jpg'),
    array('name' => 'Афганистан', 'flag' => 'Afghanistan.jpg'),
    array('name' => 'Багамы', 'flag' => 'Bahamas.jpg'),
    array('name' => 'Бангладеш', 'flag' => 'Bangladesh.jpg'),
    array('name' => 'Барбадос', 'flag' => 'Barbados.jpg'),
    array('name' => 'Бахрейн', 'flag' => 'Bahrain.jpg'),
    array('name' => 'Белиз', 'flag' => 'Belize.jpg'),
    array('name' => 'Белоруссия', 'flag' => 'Belarus.jpg'),
    array('name' => 'Бельгия', 'flag' => 'Belgium.jpg'),
    array('name' => 'Бенин', 'flag' => 'Benin.jpg'),
    array('name' => 'Болгария', 'flag' => 'Bulgaria.jpg'),
    array('name' => 'Боливия', 'flag' => 'Bolivia.jpg'),
    array('name' => 'Босния и Герцеговина', 'flag' => 'Bosnia_and_Herzegovina.jpg'),
    array('name' => 'Ботсвана', 'flag' => 'Botswana.jpg'),
    array('name' => 'Бразилия', 'flag' => 'Brazil.jpg'),
    array('name' => 'Бруней', 'flag' => 'Brunei.jpg'),
    array('name' => 'Буркина-Фасо', 'flag' => 'Burkina_Faso.jpg'),
    array('name' => 'Бурунди', 'flag' => 'Burundi.jpg'),
    array('name' => 'Бутан', 'flag' => 'Bhutan.jpg'),
    array('name' => 'Вануату', 'flag' => 'Vanuatu.jpg'),
    array('name' => 'Великобритания', 'flag' => 'United_Kingdom.jpg'),
    array('name' => 'Венгрия', 'flag' => 'Hungary.jpg'),
    array('name' => 'Венесуэла', 'flag' => 'Venezuela.jpg'),
    array('name' => 'Восточный Тимор', 'flag' => 'East_Timor.jpg'),
    array('name' => 'Вьетнам', 'flag' => 'Vietnam.jpg'),
    array('name' => 'Габон', 'flag' => 'Gabon.jpg'),
    array('name' => 'Гаити', 'flag' => 'Haiti.jpg'),
    array('name' => 'Гайана', 'flag' => 'Guyana.jpg'),
    array('name' => 'Гамбия', 'flag' => 'Gambia.jpg'),
    array('name' => 'Гана', 'flag' => 'Ghana.jpg'),
    array('name' => 'Гватемала', 'flag' => 'Guatemala.jpg'),
    array('name' => 'Гвинея', 'flag' => 'Guinea.jpg'),
    array('name' => 'Гвинея-Бисау', 'flag' => 'Guinea-Bissau.jpg'),
    array('name' => 'Германия', 'flag' => 'Germany.jpg'),
    array('name' => 'Гондурас', 'flag' => 'Honduras.jpg'),
    array('name' => 'Гренада', 'flag' => 'Grenada.jpg'),
    array('name' => 'Греция', 'flag' => 'Greece.jpg'),
    array('name' => 'Грузия', 'flag' => 'Georgia.jpg'),
    array('name' => 'Дания', 'flag' => 'Denmark.jpg'),
    array('name' => 'Демократическая Республика Конго', 'flag' => 'Democratic_Republic_of_the_Congo.jpg'),
    array('name' => 'Джибути', 'flag' => 'Djibouti.jpg'),
    array('name' => 'Доминика', 'flag' => 'Dominica.jpg'),
    array('name' => 'Доминиканская Республика', 'flag' => 'Dominican_Republic.jpg'),
    array('name' => 'Египет', 'flag' => 'Egypt.jpg'),
    array('name' => 'Замбия', 'flag' => 'Zambia.jpg'),
    array('name' => 'Зимбабве', 'flag' => 'Zimbabwe.jpg'),
    array('name' => 'Израиль', 'flag' => 'Israel.jpg'),
    array('name' => 'Индия', 'flag' => 'India.jpg'),
    array('name' => 'Индонезия', 'flag' => 'Indonesia.jpg'),
    array('name' => 'Иордания', 'flag' => 'Jordan.jpg'),
    array('name' => 'Ирак', 'flag' => 'Iraq.jpg'),
    array('name' => 'Иран', 'flag' => 'Iran.jpg'),
    array('name' => 'Ирландия', 'flag' => 'Ireland.jpg'),
    array('name' => 'Исландия', 'flag' => 'Iceland.jpg'),
    array('name' => 'Испания', 'flag' => 'Spain.jpg'),
    array('name' => 'Италия', 'flag' => 'Italy.jpg'),
    array('name' => 'Йемен', 'flag' => 'Yemen.jpg'),
    array('name' => 'Кабо-Верде', 'flag' => 'Cape_Verde.jpg'),
    array('name' => 'Казахстан', 'flag' => 'Kazakhstan.jpg'),
    array('name' => 'Камбоджа', 'flag' => 'Cambodia.jpg'),
    array('name' => 'Камерун', 'flag' => 'Cameroon.jpg'),
    array('name' => 'Канада', 'flag' => 'Canada.jpg'),
    array('name' => 'Катар', 'flag' => 'Qatar.jpg'),
    array('name' => 'Кения', 'flag' => 'Kenya.jpg'),
    array('name' => 'Кипр', 'flag' => 'Cyprus.jpg'),
    array('name' => 'Киргизия', 'flag' => 'Kyrgyzstan.jpg'),
    array('name' => 'Кирибати', 'flag' => 'Kiribati.jpg'),
    array('name' => 'КНДР', 'flag' => 'North_Korea.jpg'),
    array('name' => 'КНР', 'flag' => 'China.jpg'),
    array('name' => 'Колумбия', 'flag' => 'Colombia.jpg'),
    array('name' => 'Коморы', 'flag' => 'Comoros.jpg'),
    array('name' => 'Коста-Рика', 'flag' => 'Costa_Rica.jpg'),
    array('name' => 'Кот-д’Ивуар', 'flag' => 'Cote_dIvoire.jpg'),
    array('name' => 'Куба', 'flag' => 'Cuba.jpg'),
    array('name' => 'Кувейт', 'flag' => 'Kuwait.jpg'),
    array('name' => 'Лаос', 'flag' => 'Laos.jpg'),
    array('name' => 'Латвия', 'flag' => 'Latvia.jpg'),
    array('name' => 'Лесото', 'flag' => 'Lesotho.jpg'),
    array('name' => 'Либерия', 'flag' => 'Liberia.jpg'),
    array('name' => 'Ливан', 'flag' => 'Lebanon.jpg'),
    array('name' => 'Ливия', 'flag' => 'Libya.jpg'),
    array('name' => 'Литва', 'flag' => 'Lithuania.jpg'),
    array('name' => 'Лихтенштейн', 'flag' => 'Liechtenstein.jpg'),
    array('name' => 'Люксембург', 'flag' => 'Luxembourg.jpg'),
    array('name' => 'Маврикий', 'flag' => 'Mauritius.jpg'),
    array('name' => 'Мавритания', 'flag' => 'Mauritania.jpg'),
    array('name' => 'Мадагаскар', 'flag' => 'Madagascar.jpg'),
    array('name' => 'Македония', 'flag' => 'Macedonia.jpg'),
    array('name' => 'Малави', 'flag' => 'Malawi.jpg'),
    array('name' => 'Малайзия', 'flag' => 'Malaysia.jpg'),
    array('name' => 'Мали', 'flag' => 'Mali.jpg'),
    array('name' => 'Мальдивы', 'flag' => 'Maldives.jpg'),
    array('name' => 'Мальта', 'flag' => 'Malta.jpg'),
    array('name' => 'Марокко', 'flag' => 'Morocco.jpg'),
    array('name' => 'Маршалловы Острова', 'flag' => 'Marshall_Islands.jpg'),
    array('name' => 'Мексика', 'flag' => 'Mexico.jpg'),
    array('name' => 'Мозамбик', 'flag' => 'Mozambique.jpg'),
    array('name' => 'Молдавия', 'flag' => 'Moldova.jpg'),
    array('name' => 'Монако', 'flag' => 'Monaco.jpg'),
    array('name' => 'Монголия', 'flag' => 'Mongolia.jpg'),
    array('name' => 'Мьянма', 'flag' => 'Myanmar.jpg'),
    array('name' => 'Намибия', 'flag' => 'Namibia.jpg'),
    array('name' => 'Науру', 'flag' => 'Nauru.jpg'),
    array('name' => 'Непал', 'flag' => 'Nepal.jpg'),
    array('name' => 'Нигер', 'flag' => 'Niger.jpg'),
    array('name' => 'Нигерия', 'flag' => 'Nigeria.jpg'),
    array('name' => 'Нидерланды', 'flag' => 'Netherlands.jpg'),
    array('name' => 'Никарагуа', 'flag' => 'Nicaragua.jpg'),
    array('name' => 'Новая Зеландия', 'flag' => 'New_Zealand.jpg'),
    array('name' => 'Норвегия', 'flag' => 'Norway.jpg'),
    array('name' => 'ОАЭ', 'flag' => 'United_Arab_Emirates.jpg'),
    array('name' => 'Оман', 'flag' => 'Oman.jpg'),
    array('name' => 'Пакистан', 'flag' => 'Pakistan.jpg'),
    array('name' => 'Палау', 'flag' => 'Palau.jpg'),
    array('name' => 'Панама', 'flag' => 'Panama.jpg'),
    array('name' => 'Папуа — Новая Гвинея', 'flag' => 'Papua_New_Guinea.jpg'),
    array('name' => 'Парагвай', 'flag' => 'Paraguay.jpg'),
    array('name' => 'Перу', 'flag' => 'Peru.jpg'),
    array('name' => 'Польша', 'flag' => 'Poland.jpg'),
    array('name' => 'Португалия', 'flag' => 'Portugal.jpg'),
    array('name' => 'Республика Конго', 'flag' => 'Republic_of_the_Congo.jpg'),
    array('name' => 'Республика Корея', 'flag' => 'South_Korea.jpg'),
    array('name' => 'Россия', 'flag' => 'Russia.jpg'),
    array('name' => 'Руанда', 'flag' => 'Rwanda.jpg'),
    array('name' => 'Румыния', 'flag' => 'Romania.jpg'),
    array('name' => 'Сальвадор', 'flag' => 'El_Salvador.jpg'),
    array('name' => 'Самоа', 'flag' => 'Samoa.jpg'),
    array('name' => 'Сан-Марино', 'flag' => 'San_Marino.jpg'),
    array('name' => 'Сан-Томе и Принсипи', 'flag' => 'Sao_Tome_and_Principe.jpg'),
    array('name' => 'Саудовская Аравия', 'flag' => 'Saudi_Arabia.jpg'),
    array('name' => 'Свазиленд', 'flag' => 'Swaziland.jpg'),
    array('name' => 'Сейшельские Острова', 'flag' => 'Seychelles.jpg'),
    array('name' => 'Сенегал', 'flag' => 'Senegal.jpg'),
    array('name' => 'Сент-Винсент и Гренадины', 'flag' => 'Saint_Vincent_and_the_Grenadines.jpg'),
    array('name' => 'Сент-Китс и Невис', 'flag' => 'Saint_Kitts_and_Nevis.jpg'),
    array('name' => 'Сент-Люсия', 'flag' => 'Saint_Lucia.jpg'),
    array('name' => 'Сербия', 'flag' => 'Serbia.jpg'),
    array('name' => 'Сингапур', 'flag' => 'Singapore.jpg'),
    array('name' => 'Сирия', 'flag' => 'Syria.jpg'),
    array('name' => 'Словакия', 'flag' => 'Slovakia.jpg'),
    array('name' => 'Словения', 'flag' => 'Slovenia.jpg'),
    array('name' => 'Соломоновы Острова', 'flag' => 'Solomon_Islands.jpg'),
    array('name' => 'Сомали', 'flag' => 'Somalia.jpg'),
    array('name' => 'Судан', 'flag' => 'Sudan.jpg'),
    array('name' => 'Суринам', 'flag' => 'Suriname.jpg'),
    array('name' => 'США', 'flag' => 'United_States.jpg'),
    array('name' => 'Сьерра-Леоне', 'flag' => 'Sierra_Leone.jpg'),
    array('name' => 'Таджикистан', 'flag' => 'Tajikistan.jpg'),
    array('name' => 'Таиланд', 'flag' => 'Thailand.jpg'),
    array('name' => 'Танзания', 'flag' => 'Tanzania.jpg'),
    array('name' => 'Того', 'flag' => 'Togo.jpg'),
    array('name' => 'Тонга', 'flag' => 'Tonga.jpg'),
    array('name' => 'Тринидад и Тобаго', 'flag' => 'Trinidad_and_Tobago.jpg'),
    array('name' => 'Тувалу', 'flag' => 'Tuvalu.jpg'),
    array('name' => 'Тунис', 'flag' => 'Tunisia.jpg'),
    array('name' => 'Туркмения', 'flag' => 'Turkmenistan.jpg'),
    array('name' => 'Турция', 'flag' => 'Turkey.jpg'),
    array('name' => 'Уганда', 'flag' => 'Uganda.jpg'),
    array('name' => 'Узбекистан', 'flag' => 'Uzbekistan.jpg'),
    array('name' => 'Украина', 'flag' => 'Ukraine.jpg'),
    array('name' => 'Уругвай', 'flag' => 'Uruguay.jpg'),
    array('name' => 'Федеративные Штаты Микронезии', 'flag' => 'Micronesia.jpg'),
    array('name' => 'Фиджи', 'flag' => 'Fiji.jpg'),
    array('name' => 'Филиппины', 'flag' => 'Philippines.jpg'),
    array('name' => 'Финляндия', 'flag' => 'Finland.jpg'),
    array('name' => 'Франция', 'flag' => 'France.jpg'),
    array('name' => 'Хорватия', 'flag' => 'Croatia.jpg'),
    array('name' => 'Центральноафриканская Республика', 'flag' => 'Central_African_Republic.jpg'),
    array('name' => 'Чад', 'flag' => 'Chad.jpg'),
    array('name' => 'Черногория', 'flag' => 'Montenegro.jpg'),
    array('name' => 'Чехия', 'flag' => 'Czech_Republic.jpg'),
    array('name' => 'Чили', 'flag' => 'Chile.jpg'),
    array('name' => 'Швейцария', 'flag' => 'Switzerland.jpg'),
    array('name' => 'Швеция', 'flag' => 'Sweden.jpg'),
    array('name' => 'Шри-Ланка', 'flag' => 'Sri_Lanka.jpg'),
    array('name' => 'Эквадор', 'flag' => 'Ecuador.jpg'),
    array('name' => 'Экваториальная Гвинея', 'flag' => 'Equatorial_Guinea.jpg'),
    array('name' => 'Эритрея', 'flag' => 'Eritrea.jpg'),
    array('name' => 'Эстония', 'flag' => 'Estonia.jpg'),
    array('name' => 'Эфиопия', 'flag' => 'Ethiopia.jpg'),
    array('name' => 'ЮАР', 'flag' => 'South_Africa.jpg'),
    array('name' => 'Южный Судан', 'flag' => 'South_Sudan.jpg'),
    array('name' => 'Ямайка', 'flag' => 'Jamaica.jpg'),
    array('name' => 'Япония', 'flag' => 'Japan.jpg')
);


echo $twig->render('countries.html', array('countries' => $countries));